### ISSUE TITLE
打包iOS端App得有iOS开发者账号吧？

### ISSUE THREAD

**Issue by nodzhang** [qingmei2/FlutterGitHubApp#1]
如题，多谢。

**Comment by qingmei2** [comment]
@nodzhang 

是的，还需要iOS企业证书签名，因为是练手的项目，想要查看iOS设备上的运行效果的话，直接拉下代码后本地安装运行在iOS的模拟器上即可。

![](https://raw.githubusercontent.com/CarGuo/GSYGithubAppFlutter/master/ios_wait.png)
