### ISSUE TITLE
登陆不了

### ISSUE THREAD

**Issue by ChandlerZeng** [qingmei2/FlutterGitHubApp#3]
点击登陆一直显示loading,没有成功也没有失败的回调

**Comment by ChandlerZeng** [comment]
![image](https://user-images.githubusercontent.com/22787673/60865426-96a92500-a258-11e9-9296-94a2f7539c32.png)

**Comment by qingmei2** [comment]
@ChandlerZeng 

应该是之前的代码有点问题，最新代码中已更新

参考：

4db2ef4d9dcbd

**Comment by qingmei2** [comment]
4db2ef4d9dcbd
